export const EventTypes = {
  // Auth
  AUTH: 'AUTH',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',

  // Messages
  SEND_MESSAGE: 'SEND_MESSAGE',
  NEW_MESSAGE: 'NEW_MESSAGE',
  MESSAGE_SENT: 'MESSAGE_SENT',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  MESSAGE_EDITED: 'MESSAGE_EDITED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',

  // Message Content
  REPLY: 'REPLY',
  REPLY_MESSAGE: 'REPLY_MESSAGE',
  FORWARD_MESSAGE: 'FORWARD_MESSAGE',
  REACTION: 'REACTION',
  MESSAGE_REACTION: 'MESSAGE_REACTION',

  // Fetching
  GET_MESSAGES: 'GET_MESSAGES',
  MESSAGES: 'MESSAGES',
  GET_CONVERSATIONS: 'GET_CONVERSATIONS',
  CONVERSATIONS: 'CONVERSATIONS',

  // Typing & Read
  TYPING: 'TYPING',
  READ: 'READ',
  READ_RECEIPT: 'READ_RECEIPT',

  // Presence
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  LAST_SEEN: 'LAST_SEEN',
  PRESENCE_UPDATE: 'PRESENCE_UPDATE',

  // Groups
  CREATE_GROUP: 'CREATE_GROUP',
  CREATE_GROUP_CHAT: 'CREATE_GROUP_CHAT',
  GROUP_CREATED: 'GROUP_CREATED',
  JOIN_GROUP: 'JOIN_GROUP',
  LEAVE_GROUP: 'LEAVE_GROUP',
  GROUP_JOINED: 'GROUP_JOINED',
  GROUP_LEFT: 'GROUP_LEFT',
  GROUP_MEMBER_JOINED: 'GROUP_MEMBER_JOINED',
  GROUP_MEMBER_LEFT: 'GROUP_MEMBER_LEFT',
  UPDATE_GROUP: 'UPDATE_GROUP',
  GROUP_UPDATED: 'GROUP_UPDATED',
  REMOVE_MEMBER: 'REMOVE_MEMBER',
  MEMBER_REMOVED: 'MEMBER_REMOVED',

  // Group Admin
  MAKE_ADMIN: 'MAKE_ADMIN',
  REMOVE_ADMIN: 'REMOVE_ADMIN',
  ADMIN_ADDED: 'ADMIN_ADDED',
  ADMIN_REMOVED: 'ADMIN_REMOVED',

  // Pins
  PIN_MESSAGE: 'PIN_MESSAGE',
  UNPIN_MESSAGE: 'UNPIN_MESSAGE',
  MESSAGE_PINNED: 'MESSAGE_PINNED',
  MESSAGE_UNPINNED: 'MESSAGE_UNPINNED',
  GET_PINNED_MESSAGES: 'GET_PINNED_MESSAGES',
  PINNED_MESSAGES: 'PINNED_MESSAGES',

  // Block/Unblock
  BLOCK_USER: 'BLOCK_USER',
  UNBLOCK_USER: 'UNBLOCK_USER',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',
  GET_BLOCKED_USERS: 'GET_BLOCKED_USERS',
  BLOCKED_USERS: 'BLOCKED_USERS',

  // Media
  UPLOAD_MEDIA: 'UPLOAD_MEDIA',
  MEDIA_UPLOADED: 'MEDIA_UPLOADED',

  // Search
  SEARCH_MESSAGES: 'SEARCH_MESSAGES',
  SEARCH_RESULTS: 'SEARCH_RESULTS',
  SEARCH_USERS: 'SEARCH_USERS',
  USER_SEARCH: 'USER_SEARCH',

  // Users
  GET_USER: 'GET_USER',
  USER_PROFILE: 'USER_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  PROFILE_UPDATED: 'PROFILE_UPDATED',

  // Settings
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',

  // Misc
  DISCONNECT: 'DISCONNECT',
  ERROR: 'ERROR',
  WS_ERROR: 'WS_ERROR',
  PING: 'PING',
  PONG: 'PONG',
  ACKNOWLEDGE: 'ACKNOWLEDGE',
} as const;

export type EventType = typeof EventTypes[keyof typeof EventTypes];